name: Despliegue A Github Pages Del SPA Con Vite

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DEPLOY_BASE_URL: ${{ vars.DEPLOY_BASE_URL }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
        
      - name: Configurar NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Instalar Dependencias
        run: npm install

      - name: Verificar Variables De Ambiente
        run: echo "DEPLOY_BASE_URL $DEPLOY_BASE_URL"

      - name: Compilar Proyecto
        run: npm run build

      - name: Configurar Github Pages
        uses: actions/configure-pages@v5

      - name: Subir Compilado A Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Publicar Pagina En Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
